name: Actualizar README con IA

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 2 * * 1'  # Cada lunes a las 2am UTC

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - run: pip install openai

      - name: Ejecutar script Python
        env:
          OPENAI_API_KEY: ${{ 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 }}
        run: python .github/scripts/generar_readme_ia.py

      - name: Commit y push si hubo cambios
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add README.md
          git diff --cached --quiet || git commit -m "Actualizar README con IA"
          git push
